blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://github.com/testradar/testradar-community-issue-tracker/discussions
    about: Please ask and answer questions here.
